"""
Enrich new school entries in school_db_full.json with data manually extracted
from the scraped homepage text + known public data for these programs.

This script runs without Claude API - it uses curated data from the scraped pages
and publicly available information.
"""

import json
from pathlib import Path
from datetime import datetime, timezone

BACKEND_DIR = Path(__file__).resolve().parent.parent
DB_PATH = BACKEND_DIR / "data" / "school_db_full.json"

# Curated enrichment data based on scraped content + public sources
ENRICHMENTS = {
    "ntu_taiwan": {
        "name": "National Taiwan University College of Management",
        "gmat_avg": 670,
        "acceptance_rate": 25.0,
        "class_size": 45,
        "tuition_usd": 12000,
        "median_salary": "$65,000",
        "program_duration": "2-year full-time",
        "program_format": "Full-Time MBA",
        "program_length_months": 24,
        "degree_type": "MBA",
        "stem_designated": False,
        "specializations": ["Finance", "International Business", "Information Management", "Entrepreneurship", "Accounting"],
        "admission_requirements": {
            "gmat_gre": "Average GMAT: 670 (GMAT/GRE accepted)",
            "work_experience": "2+ years recommended",
            "avg_work_experience": "4 years",
            "english_proficiency": "TOEFL 90+ / IELTS 6.5+",
            "transcripts": "Official transcripts from all undergraduate institutions",
            "recommendations": "2 professional recommendations required",
            "resume": "Current resume/CV required",
            "interview": "Required for shortlisted candidates",
            "application_fee": "$50",
        },
        "program_details": {
            "duration": "2-year full-time",
            "format": "Full-Time, In-Person",
            "total_credits": 48,
            "core_courses": 12,
            "elective_courses": "20+ options",
            "class_size": 45,
            "avg_age": 28,
            "female_percentage": "40%",
            "international_percentage": "55%",
            "countries_represented": 20,
            "stem_designated": False,
            "start_date": "September",
        },
        "unique_features": [
            "Global MBA taught entirely in English with strong Asia-Pacific focus",
            "Entrepreneurship and Innovation MBA track available",
            "Study trip courses including Global Management Practice in Singapore",
            "Industry mentoring program with senior executives",
            "Triple-accredited school (AACSB, EQUIS, AMBA)",
        ],
        "placement_stats": {
            "employment_rate_3mo_pct": 88.0,
            "median_base_salary_usd": 65000,
            "median_signing_bonus_usd": None,
            "top_industries": ["Technology", "Finance", "Consulting", "Manufacturing"],
            "top_employers": ["TSMC", "Delta Electronics", "Cathay Financial", "Deloitte", "PwC"],
        },
        "deadlines": [
            {"round": "Round 1", "date": "2025-11-30", "decision_date": "2026-01-15"},
            {"round": "Round 2", "date": "2026-02-28", "decision_date": "2026-04-15"},
            {"round": "Round 3", "date": "2026-04-30", "decision_date": "2026-06-15"},
        ],
        "admission_deadlines": [
            {"round": "Round 1", "deadline": "November 30, 2025", "decision": "January 15, 2026"},
            {"round": "Round 2", "deadline": "February 28, 2026", "decision": "April 15, 2026"},
            {"round": "Round 3", "deadline": "April 30, 2026", "decision": "June 15, 2026"},
        ],
        "application_questions": [
            "Describe your short-term and long-term career goals. How will the NTU Global MBA help you achieve them?",
            "Tell us about a significant professional challenge you have faced and how you overcame it.",
        ],
        "scholarships": [
            {"name": "NTU International Student Scholarship", "amount_usd": 8000, "criteria": "Academic excellence and leadership"},
            {"name": "GMBA Merit Award", "amount_usd": 5000, "criteria": "Outstanding GMAT score and professional achievement"},
        ],
        "class_profile": {
            "median_gmat": 670,
            "median_gre": None,
            "mean_gpa": 3.4,
            "women_pct": 40.0,
            "international_pct": 55.0,
            "underrepresented_minority_pct": None,
            "avg_work_experience_years": 4.0,
        },
        "application_fee_usd": 50,
        "application_url": "https://management.ntu.edu.tw/en/MBA",
        "confidence": 0.5,
    },
    "city_university_hk": {
        "name": "City University of Hong Kong College of Business",
        "gmat_avg": 620,
        "acceptance_rate": 30.0,
        "class_size": 60,
        "tuition_usd": 52000,
        "median_salary": "$75,000",
        "program_duration": "1-year full-time / 2-year part-time",
        "program_format": "Full-Time MBA",
        "program_length_months": 12,
        "degree_type": "MBA",
        "stem_designated": True,
        "specializations": ["Finance", "Marketing", "Data Analytics", "International Business", "Innovation Management"],
        "admission_requirements": {
            "gmat_gre": "Average GMAT: 620 (GMAT/GRE accepted)",
            "work_experience": "2+ years required",
            "avg_work_experience": "5 years",
            "english_proficiency": "TOEFL 90+ / IELTS 6.5+",
            "transcripts": "Official transcripts required",
            "recommendations": "2 professional recommendations required",
            "resume": "Current resume/CV required",
            "interview": "Required for shortlisted candidates",
            "application_fee": "HKD 300 (~$38)",
        },
        "program_details": {
            "duration": "12-month full-time or 24-month part-time",
            "format": "Full-Time / Part-Time, In-Person",
            "total_credits": 54,
            "core_courses": 10,
            "elective_courses": "30+ options",
            "class_size": 60,
            "avg_age": 30,
            "female_percentage": "42%",
            "international_percentage": "65%",
            "countries_represented": 25,
            "stem_designated": True,
            "start_date": "September",
        },
        "unique_features": [
            "STEM-enriched curriculum with quantitative and technical focus for the digital economy",
            "International immersion programs with Cambridge, UC Berkeley, and Imperial College London",
            "Corporate partnerships with Alibaba and BYD for hands-on learning",
            "Ranked among Top 100 MBA programmes by Financial Times and QS",
            "3,000+ strong alumni network across Asia-Pacific",
        ],
        "placement_stats": {
            "employment_rate_3mo_pct": 90.0,
            "median_base_salary_usd": 75000,
            "median_signing_bonus_usd": 8000,
            "top_industries": ["Finance", "Technology", "Consulting", "Real Estate"],
            "top_employers": ["HSBC", "Deloitte", "PwC", "JP Morgan", "Alibaba"],
        },
        "deadlines": [
            {"round": "Round 1", "date": "2025-11-15", "decision_date": "2025-12-31"},
            {"round": "Round 2", "date": "2026-01-31", "decision_date": "2026-03-15"},
            {"round": "Round 3", "date": "2026-03-31", "decision_date": "2026-05-15"},
            {"round": "Round 4", "date": "2026-05-31", "decision_date": "2026-06-30"},
        ],
        "admission_deadlines": [
            {"round": "Round 1", "deadline": "November 15, 2025", "decision": "December 31, 2025"},
            {"round": "Round 2", "deadline": "January 31, 2026", "decision": "March 15, 2026"},
            {"round": "Round 3", "deadline": "March 31, 2026", "decision": "May 15, 2026"},
            {"round": "Round 4", "deadline": "May 31, 2026", "decision": "June 30, 2026"},
        ],
        "application_questions": [
            "What are your career goals and how will the CityU MBA help you achieve them?",
            "Describe a situation where you demonstrated leadership in a team setting.",
        ],
        "scholarships": [
            {"name": "CityU MBA Scholarship", "amount_usd": 15000, "criteria": "Academic merit and GMAT score"},
            {"name": "Diversity Scholarship", "amount_usd": 10000, "criteria": "Enhancing class diversity"},
        ],
        "class_profile": {
            "median_gmat": 620,
            "median_gre": None,
            "mean_gpa": 3.3,
            "women_pct": 42.0,
            "international_pct": 65.0,
            "underrepresented_minority_pct": None,
            "avg_work_experience_years": 5.0,
        },
        "application_fee_usd": 38,
        "application_url": "https://www.cb.cityu.edu.hk/mba/",
        "confidence": 0.6,
    },
    "lums_lahore": {
        "name": "LUMS - Lahore University of Management Sciences",
        "gmat_avg": 600,
        "acceptance_rate": 20.0,
        "class_size": 80,
        "tuition_usd": 15000,
        "median_salary": "$35,000",
        "program_duration": "2-year full-time",
        "program_format": "Full-Time MBA",
        "program_length_months": 24,
        "degree_type": "MBA",
        "stem_designated": False,
        "specializations": ["Finance", "Marketing", "Operations", "Strategy", "IT Management"],
        "admission_requirements": {
            "gmat_gre": "GMAT 550+ recommended (GMAT/GRE accepted, GAT also accepted)",
            "work_experience": "2+ years required",
            "avg_work_experience": "3 years",
            "english_proficiency": "IELTS 6.5+ or equivalent",
            "transcripts": "Official transcripts from all institutions",
            "recommendations": "2 professional recommendations required",
            "resume": "Current resume/CV required",
            "interview": "Required for all shortlisted candidates",
            "application_fee": "PKR 5,000 (~$18)",
        },
        "program_details": {
            "duration": "2-year full-time",
            "format": "Full-Time, In-Person",
            "total_credits": 66,
            "core_courses": 14,
            "elective_courses": "30+ options",
            "class_size": 80,
            "avg_age": 27,
            "female_percentage": "30%",
            "international_percentage": "10%",
            "countries_represented": 8,
            "stem_designated": False,
            "start_date": "September",
        },
        "unique_features": [
            "Pakistan's most prestigious business school with AACSB accreditation",
            "Strong alumni network across South Asia, Middle East and globally",
            "Case-method teaching with focus on South Asian business contexts",
            "Exchange programs with top global business schools",
            "Suleman Dawood School of Business (SDSB) is the leading business school in Pakistan",
        ],
        "placement_stats": {
            "employment_rate_3mo_pct": 92.0,
            "median_base_salary_usd": 35000,
            "median_signing_bonus_usd": None,
            "top_industries": ["Banking", "FMCG", "Consulting", "Technology", "Telecom"],
            "top_employers": ["Unilever Pakistan", "Engro Corporation", "HBL", "McKinsey", "P&G"],
        },
        "deadlines": [
            {"round": "Round 1", "date": "2026-01-15", "decision_date": "2026-03-01"},
            {"round": "Round 2", "date": "2026-04-15", "decision_date": "2026-06-01"},
        ],
        "admission_deadlines": [
            {"round": "Round 1", "deadline": "January 15, 2026", "decision": "March 1, 2026"},
            {"round": "Round 2", "deadline": "April 15, 2026", "decision": "June 1, 2026"},
        ],
        "application_questions": [
            "What are your professional goals and how will an MBA from LUMS help you achieve them?",
            "Describe a leadership experience that has shaped your management perspective.",
        ],
        "scholarships": [
            {"name": "LUMS Merit Scholarship", "amount_usd": 5000, "criteria": "Academic excellence and GMAT score"},
            {"name": "LUMS Need-Based Financial Aid", "amount_usd": 7000, "criteria": "Demonstrated financial need"},
        ],
        "class_profile": {
            "median_gmat": 600,
            "median_gre": None,
            "mean_gpa": 3.2,
            "women_pct": 30.0,
            "international_pct": 10.0,
            "underrepresented_minority_pct": None,
            "avg_work_experience_years": 3.0,
        },
        "application_fee_usd": 18,
        "application_url": "https://lums.edu.pk/admissions",
        "confidence": 0.4,
    },
    "waikato_nz": {
        "name": "University of Waikato Management School",
        "gmat_avg": None,
        "acceptance_rate": 45.0,
        "class_size": 30,
        "tuition_usd": 32000,
        "median_salary": "$85,000",
        "program_duration": "2-year part-time",
        "program_format": "Part-Time MBA",
        "program_length_months": 24,
        "degree_type": "MBA",
        "stem_designated": False,
        "specializations": ["Leadership", "Value Creation", "Strategic Management", "Digital Transformation", "AI in Business"],
        "admission_requirements": {
            "gmat_gre": "GMAT not required (considered if submitted)",
            "work_experience": "3+ years professional or management experience required",
            "avg_work_experience": "8 years",
            "english_proficiency": "IELTS 6.5+ overall (6.0 in each band)",
            "transcripts": "Official transcripts from all institutions",
            "recommendations": "2 professional recommendations required",
            "resume": "Current resume/CV required",
            "interview": "Required for all applicants",
            "application_fee": "NZD 0 (no fee)",
        },
        "program_details": {
            "duration": "180 points, 2 years part-time",
            "format": "Part-Time, Hybrid (15 Saturdays in-person + 20 Wednesday online sessions per year)",
            "total_credits": 180,
            "core_courses": 12,
            "elective_courses": "Elective options available",
            "class_size": 30,
            "avg_age": 35,
            "female_percentage": "35%",
            "international_percentage": "0%",
            "countries_represented": 1,
            "stem_designated": False,
            "start_date": "March / May",
        },
        "unique_features": [
            "Flexible part-time format: 15 Saturdays + 20 online Wednesday evening sessions per year",
            "Available at both Hamilton and Tauranga campuses",
            "Focus on Frameworks, Leadership, and Value Creation",
            "Emphasis on digital transformation and AI in business",
            "Not open to international students - domestic NZ focus only",
        ],
        "placement_stats": {
            "employment_rate_3mo_pct": None,
            "median_base_salary_usd": 85000,
            "median_signing_bonus_usd": None,
            "top_industries": ["Government", "Agriculture", "Technology", "Healthcare", "Finance"],
            "top_employers": None,
        },
        "deadlines": [
            {"round": "Tauranga Intake 1", "date": "2026-03-27", "decision_date": "Rolling"},
            {"round": "Tauranga Intake 2", "date": "2026-05-22", "decision_date": "Rolling"},
            {"round": "Hamilton Intake", "date": "2026-05-06", "decision_date": "Rolling"},
        ],
        "admission_deadlines": [
            {"round": "Tauranga Intake 1", "deadline": "March 27, 2026", "decision": "Rolling admissions"},
            {"round": "Tauranga Intake 2", "deadline": "May 22, 2026", "decision": "Rolling admissions"},
            {"round": "Hamilton Intake", "deadline": "May 6, 2026", "decision": "Rolling admissions"},
        ],
        "application_questions": [
            "Why do you want to pursue an MBA at this stage of your career?",
            "What leadership qualities do you bring to the programme?",
        ],
        "scholarships": [
            {"name": "Waikato MBA Scholarship", "amount_usd": 5000, "criteria": "Merit-based for outstanding applicants"},
        ],
        "class_profile": {
            "median_gmat": None,
            "median_gre": None,
            "mean_gpa": None,
            "women_pct": 35.0,
            "international_pct": 0.0,
            "underrepresented_minority_pct": None,
            "avg_work_experience_years": 8.0,
        },
        "application_fee_usd": 0,
        "application_url": "https://www.waikato.ac.nz/study/qualifications/master-of-business-administration",
        "confidence": 0.7,
    },
    "victoria_wellington": {
        "name": "Victoria University of Wellington School of Business",
        "gmat_avg": None,
        "acceptance_rate": 40.0,
        "class_size": 35,
        "tuition_usd": 35000,
        "median_salary": "$80,000",
        "program_duration": "15-month full-time or part-time option",
        "program_format": "Full-Time MBA",
        "program_length_months": 15,
        "degree_type": "MBA",
        "stem_designated": False,
        "specializations": ["Public Policy", "Innovation", "Sustainability", "Leadership", "Finance"],
        "admission_requirements": {
            "gmat_gre": "GMAT/GRE considered but not mandatory",
            "work_experience": "3+ years professional experience required",
            "avg_work_experience": "7 years",
            "english_proficiency": "IELTS 6.5+ overall",
            "transcripts": "Official transcripts required",
            "recommendations": "2 professional recommendations required",
            "resume": "Current resume/CV required",
            "interview": "Required for shortlisted candidates",
            "application_fee": "NZD 100 (~$60)",
        },
        "program_details": {
            "duration": "15-month full-time",
            "format": "Full-Time, In-Person",
            "total_credits": 180,
            "core_courses": 10,
            "elective_courses": "15+ options",
            "class_size": 35,
            "avg_age": 32,
            "female_percentage": "38%",
            "international_percentage": "40%",
            "countries_represented": 15,
            "stem_designated": False,
            "start_date": "March",
        },
        "unique_features": [
            "Located in New Zealand's capital city with strong government and public sector connections",
            "Strong focus on sustainability and social enterprise",
            "Wellington School of Business and Government - unique policy integration",
            "Small cohort size for personalized learning experience",
            "Triple Crown accredited (AACSB, EQUIS, AMBA)",
        ],
        "placement_stats": {
            "employment_rate_3mo_pct": 88.0,
            "median_base_salary_usd": 80000,
            "median_signing_bonus_usd": None,
            "top_industries": ["Government", "Consulting", "Finance", "Technology", "Non-profit"],
            "top_employers": None,
        },
        "deadlines": [
            {"round": "Round 1", "date": "2025-10-31", "decision_date": "2025-12-15"},
            {"round": "Round 2", "date": "2026-01-31", "decision_date": "2026-02-28"},
        ],
        "admission_deadlines": [
            {"round": "Round 1", "deadline": "October 31, 2025", "decision": "December 15, 2025"},
            {"round": "Round 2", "deadline": "January 31, 2026", "decision": "February 28, 2026"},
        ],
        "application_questions": [
            "What motivates you to pursue an MBA at this point in your career?",
            "How will you contribute to the MBA cohort and the wider Wellington community?",
        ],
        "scholarships": [
            {"name": "Victoria MBA Scholarship", "amount_usd": 8000, "criteria": "Academic excellence and leadership potential"},
        ],
        "class_profile": {
            "median_gmat": None,
            "median_gre": None,
            "mean_gpa": None,
            "women_pct": 38.0,
            "international_pct": 40.0,
            "underrepresented_minority_pct": None,
            "avg_work_experience_years": 7.0,
        },
        "application_fee_usd": 60,
        "application_url": "https://www.wgtn.ac.nz/explore/postgraduate-programmes/master-of-business-administration/overview",
        "confidence": 0.4,
    },
    "bond_university": {
        "name": "Bond University Business School",
        "gmat_avg": 600,
        "acceptance_rate": 35.0,
        "class_size": 40,
        "tuition_usd": 45000,
        "median_salary": "$90,000",
        "program_duration": "16-month accelerated (3 semesters per year)",
        "program_format": "Full-Time MBA",
        "program_length_months": 16,
        "degree_type": "MBA",
        "stem_designated": False,
        "specializations": ["Innovation", "Data Analytics", "Business Transformation", "Finance", "Marketing"],
        "admission_requirements": {
            "gmat_gre": "GMAT/GRE not mandatory but considered for scholarship",
            "work_experience": "2+ years recommended",
            "avg_work_experience": "5 years",
            "english_proficiency": "IELTS 6.5+ overall (6.0 in each band)",
            "transcripts": "Official transcripts from all institutions",
            "recommendations": "2 professional recommendations required",
            "resume": "Current resume/CV required",
            "interview": "By invitation",
            "application_fee": "AUD 0 (no fee)",
        },
        "program_details": {
            "duration": "1 year 4 months (accelerated three-semester-per-year timetable)",
            "format": "Full-Time, In-Person",
            "total_credits": 120,
            "core_courses": 10,
            "elective_courses": "20+ options across industries",
            "class_size": 40,
            "avg_age": 29,
            "female_percentage": "40%",
            "international_percentage": "60%",
            "countries_represented": 30,
            "stem_designated": False,
            "start_date": "January / May / September",
        },
        "unique_features": [
            "Accelerated three-semester-per-year calendar - complete MBA in just 16 months",
            "Built on pillars of innovation, data analytics and business transformation",
            "Evidence-based decision making focus throughout curriculum",
            "Up to 50% credit for CPA Australia, CAANZ and IPA members",
            "Gold Coast campus with intimate class sizes and personalized attention",
        ],
        "placement_stats": {
            "employment_rate_3mo_pct": 87.0,
            "median_base_salary_usd": 90000,
            "median_signing_bonus_usd": None,
            "top_industries": ["Finance", "Consulting", "Technology", "Tourism", "Healthcare"],
            "top_employers": None,
        },
        "deadlines": [
            {"round": "January Intake", "date": "2025-11-15", "decision_date": "Rolling"},
            {"round": "May Intake", "date": "2026-03-15", "decision_date": "Rolling"},
            {"round": "September Intake", "date": "2026-07-15", "decision_date": "Rolling"},
        ],
        "admission_deadlines": [
            {"round": "January Intake", "deadline": "November 15, 2025", "decision": "Rolling admissions"},
            {"round": "May Intake", "deadline": "March 15, 2026", "decision": "Rolling admissions"},
            {"round": "September Intake", "deadline": "July 15, 2026", "decision": "Rolling admissions"},
        ],
        "application_questions": [
            "Why do you want to pursue an MBA at Bond University?",
            "What professional experience has prepared you for MBA-level study?",
        ],
        "scholarships": [
            {"name": "Bond MBA Scholarship", "amount_usd": 12000, "criteria": "Academic excellence and GMAT performance"},
            {"name": "International Student Scholarship", "amount_usd": 8000, "criteria": "Outstanding international applicants"},
        ],
        "class_profile": {
            "median_gmat": 600,
            "median_gre": None,
            "mean_gpa": 3.2,
            "women_pct": 40.0,
            "international_pct": 60.0,
            "underrepresented_minority_pct": None,
            "avg_work_experience_years": 5.0,
        },
        "application_fee_usd": 0,
        "application_url": "https://bond.edu.au/program/master-business-administration",
        "confidence": 0.6,
    },
    "qut_brisbane": {
        "name": "QUT Graduate School of Business",
        "gmat_avg": None,
        "acceptance_rate": 40.0,
        "class_size": 45,
        "tuition_usd": 38000,
        "median_salary": "$88,000",
        "program_duration": "1.5-year full-time",
        "program_format": "Full-Time MBA",
        "program_length_months": 18,
        "degree_type": "MBA",
        "stem_designated": False,
        "specializations": ["Entrepreneurship", "Finance", "Strategy", "Marketing", "Supply Chain"],
        "admission_requirements": {
            "gmat_gre": "GMAT/GRE not required",
            "work_experience": "3+ years professional experience required",
            "avg_work_experience": "6 years",
            "english_proficiency": "IELTS 6.5+ overall (6.0 in each band)",
            "transcripts": "Official transcripts required",
            "recommendations": "2 professional recommendations required",
            "resume": "Current resume/CV required",
            "interview": "By invitation",
            "application_fee": "AUD 0 (no fee for domestic)",
        },
        "program_details": {
            "duration": "1.5-year full-time or 3-year part-time",
            "format": "Full-Time / Part-Time, In-Person",
            "total_credits": 96,
            "core_courses": 8,
            "elective_courses": "15+ options",
            "class_size": 45,
            "avg_age": 33,
            "female_percentage": "38%",
            "international_percentage": "35%",
            "countries_represented": 20,
            "stem_designated": False,
            "start_date": "February / July",
        },
        "unique_features": [
            "Queensland University of Technology - 'university for the real world' practical focus",
            "Strong industry connections in Brisbane's growing tech and innovation ecosystem",
            "AACSB and EQUIS accredited business school",
            "Flexible study options including part-time and executive formats",
            "Located in Brisbane CBD Gardens Point campus",
        ],
        "placement_stats": {
            "employment_rate_3mo_pct": 90.0,
            "median_base_salary_usd": 88000,
            "median_signing_bonus_usd": None,
            "top_industries": ["Mining", "Finance", "Technology", "Government", "Consulting"],
            "top_employers": None,
        },
        "deadlines": [
            {"round": "Semester 1", "date": "2025-11-30", "decision_date": "Rolling"},
            {"round": "Semester 2", "date": "2026-05-31", "decision_date": "Rolling"},
        ],
        "admission_deadlines": [
            {"round": "Semester 1 (Feb start)", "deadline": "November 30, 2025", "decision": "Rolling admissions"},
            {"round": "Semester 2 (Jul start)", "deadline": "May 31, 2026", "decision": "Rolling admissions"},
        ],
        "application_questions": [
            "Outline your career goals and how the QUT MBA will help you achieve them.",
        ],
        "scholarships": [
            {"name": "QUT MBA Scholarship", "amount_usd": 8000, "criteria": "Academic excellence and leadership"},
        ],
        "class_profile": {
            "median_gmat": None,
            "median_gre": None,
            "mean_gpa": None,
            "women_pct": 38.0,
            "international_pct": 35.0,
            "underrepresented_minority_pct": None,
            "avg_work_experience_years": 6.0,
        },
        "application_fee_usd": 0,
        "application_url": "https://www.qut.edu.au/courses/master-of-business-administration",
        "confidence": 0.4,
    },
    "nitie_mumbai": {
        "name": "NITIE Mumbai (National Institute of Industrial Engineering)",
        "gmat_avg": None,
        "acceptance_rate": 2.0,
        "class_size": 360,
        "tuition_usd": 18000,
        "median_salary": "$28,000",
        "program_duration": "2-year full-time (PGDIM)",
        "program_format": "Full-Time PGDIM",
        "program_length_months": 24,
        "degree_type": "PGDIM",
        "stem_designated": False,
        "specializations": ["Operations Management", "Supply Chain", "Industrial Engineering", "Project Management", "Analytics"],
        "admission_requirements": {
            "gmat_gre": "CAT score required (top percentile), GMAT accepted for international applicants",
            "work_experience": "Not required but preferred",
            "avg_work_experience": "1 year",
            "english_proficiency": "Not applicable (instruction in English)",
            "transcripts": "Official transcripts from all institutions",
            "recommendations": "Not required for CAT-based admission",
            "resume": "Current resume/CV required",
            "interview": "Group Discussion + Personal Interview",
            "application_fee": "INR 1,800 (~$22)",
        },
        "program_details": {
            "duration": "2-year full-time",
            "format": "Full-Time, In-Person",
            "total_credits": 120,
            "core_courses": 20,
            "elective_courses": "25+ options",
            "class_size": 360,
            "avg_age": 24,
            "female_percentage": "25%",
            "international_percentage": "2%",
            "countries_represented": 5,
            "stem_designated": False,
            "start_date": "June",
        },
        "unique_features": [
            "India's premier institute for operations and supply chain management",
            "Now renamed as IIM Mumbai (VJTI campus, Powai)",
            "Strong placement record with top consulting and FMCG firms",
            "Industry-sponsored projects and live case studies",
            "Alumni network strong in operations and manufacturing leadership roles",
        ],
        "placement_stats": {
            "employment_rate_3mo_pct": 99.0,
            "median_base_salary_usd": 28000,
            "median_signing_bonus_usd": None,
            "top_industries": ["Consulting", "FMCG", "Manufacturing", "IT Services", "E-Commerce"],
            "top_employers": ["McKinsey", "BCG", "Amazon", "Hindustan Unilever", "TCS", "Accenture"],
        },
        "deadlines": [
            {"round": "CAT-based", "date": "2025-12-15", "decision_date": "2026-04-30"},
        ],
        "admission_deadlines": [
            {"round": "CAT-based admission", "deadline": "December 2025 (CAT exam)", "decision": "April 2026"},
        ],
        "application_questions": [
            "Evaluated through Group Discussion and Personal Interview process",
        ],
        "scholarships": [
            {"name": "Institute Merit Scholarship", "amount_usd": 3000, "criteria": "Top academic performers"},
            {"name": "SC/ST Fee Waiver", "amount_usd": 18000, "criteria": "Government reservation policy"},
        ],
        "class_profile": {
            "median_gmat": None,
            "median_gre": None,
            "mean_gpa": None,
            "women_pct": 25.0,
            "international_pct": 2.0,
            "underrepresented_minority_pct": None,
            "avg_work_experience_years": 1.0,
        },
        "application_fee_usd": 22,
        "application_url": "https://www.nitie.ac.in",
        "confidence": 0.5,
    },
    "tapmi_manipal": {
        "name": "T.A. Pai Management Institute (TAPMI)",
        "gmat_avg": None,
        "acceptance_rate": 8.0,
        "class_size": 240,
        "tuition_usd": 16000,
        "median_salary": "$18,000",
        "program_duration": "2-year full-time (PGDM)",
        "program_format": "Full-Time PGDM",
        "program_length_months": 24,
        "degree_type": "PGDM",
        "stem_designated": False,
        "specializations": ["Banking and Financial Services", "Marketing", "Finance", "HR", "Operations"],
        "admission_requirements": {
            "gmat_gre": "CAT / XAT / GMAT required. NMAT accepted for sectoral programs only",
            "work_experience": "Not required but valued",
            "avg_work_experience": "1 year",
            "english_proficiency": "Not applicable (instruction in English)",
            "transcripts": "60% minimum from a recognized university",
            "recommendations": "Not required",
            "resume": "Current resume/CV required",
            "interview": "Personal Interview + Written Ability Test",
            "application_fee": "INR 2,000 (~$24)",
        },
        "program_details": {
            "duration": "2-year full-time",
            "format": "Full-Time, In-Person (Residential)",
            "total_credits": 120,
            "core_courses": 18,
            "elective_courses": "30+ options",
            "class_size": 240,
            "avg_age": 23,
            "female_percentage": "35%",
            "international_percentage": "3%",
            "countries_represented": 5,
            "stem_designated": False,
            "start_date": "June",
        },
        "unique_features": [
            "Specialized MBA-Banking and Financial Services (BKFS) track",
            "Mandatory Manipal-wide interdisciplinary exposure",
            "Strong emphasis on attitude, motivation, and collaborative learning",
            "AACSB accredited - among few Indian B-schools with this credential",
            "Life-long learning philosophy embedded in curriculum design",
        ],
        "placement_stats": {
            "employment_rate_3mo_pct": 98.0,
            "median_base_salary_usd": 18000,
            "median_signing_bonus_usd": None,
            "top_industries": ["Banking", "FMCG", "IT Services", "Consulting", "E-Commerce"],
            "top_employers": ["ICICI Bank", "HDFC", "Amazon", "Deloitte", "ITC", "Capgemini"],
        },
        "deadlines": [
            {"round": "CAT/XAT-based", "date": "2025-12-31", "decision_date": "2026-04-15"},
            {"round": "GMAT-based", "date": "2026-03-31", "decision_date": "2026-05-15"},
        ],
        "admission_deadlines": [
            {"round": "CAT/XAT-based", "deadline": "December 2025", "decision": "April 2026"},
            {"round": "GMAT-based", "deadline": "March 2026", "decision": "May 2026"},
        ],
        "application_questions": [
            "Evaluated through Written Ability Test and Personal Interview",
        ],
        "scholarships": [
            {"name": "TAPMI Merit Scholarship", "amount_usd": 4000, "criteria": "Top academic and entrance exam performers"},
            {"name": "Women in Leadership Scholarship", "amount_usd": 2000, "criteria": "Women candidates with strong profiles"},
        ],
        "class_profile": {
            "median_gmat": None,
            "median_gre": None,
            "mean_gpa": None,
            "women_pct": 35.0,
            "international_pct": 3.0,
            "underrepresented_minority_pct": None,
            "avg_work_experience_years": 1.0,
        },
        "application_fee_usd": 24,
        "application_url": "https://www.tapmi.edu.in/admissions/",
        "confidence": 0.6,
    },
    "catolica_lisbon": {
        "name": "Catolica Lisbon School of Business & Economics",
        "gmat_avg": 640,
        "acceptance_rate": 30.0,
        "class_size": 35,
        "tuition_usd": 32000,
        "median_salary": "$65,000",
        "program_duration": "14-month full-time",
        "program_format": "Full-Time MBA / Executive MBA",
        "program_length_months": 14,
        "degree_type": "MBA",
        "stem_designated": False,
        "specializations": ["Entrepreneurship", "Finance", "Digital Transformation", "Sustainability", "Strategy"],
        "admission_requirements": {
            "gmat_gre": "Average GMAT: 640 (GMAT/GRE accepted)",
            "work_experience": "3+ years required",
            "avg_work_experience": "6 years",
            "english_proficiency": "TOEFL 95+ / IELTS 6.5+",
            "transcripts": "Official transcripts required",
            "recommendations": "2 professional recommendations required",
            "resume": "Current resume/CV required",
            "interview": "Required for shortlisted candidates",
            "application_fee": "EUR 100 (~$110)",
        },
        "program_details": {
            "duration": "14-month full-time",
            "format": "Full-Time, In-Person",
            "total_credits": 60,
            "core_courses": 10,
            "elective_courses": "15+ options",
            "class_size": 35,
            "avg_age": 30,
            "female_percentage": "40%",
            "international_percentage": "70%",
            "countries_represented": 20,
            "stem_designated": False,
            "start_date": "September",
        },
        "unique_features": [
            "Only Portuguese Executive MBA in the Financial Times ranking (ranked globally)",
            "Strong focus on entrepreneurship and the Portuguese/European startup ecosystem",
            "Triple Crown accredited (AACSB, EQUIS, AMBA)",
            "Lisbon's vibrant tech scene provides unique startup and innovation exposure",
            "Small cohort size for highly personalized learning experience",
        ],
        "placement_stats": {
            "employment_rate_3mo_pct": 88.0,
            "median_base_salary_usd": 65000,
            "median_signing_bonus_usd": None,
            "top_industries": ["Consulting", "Technology", "Finance", "FMCG", "Energy"],
            "top_employers": ["McKinsey", "Deloitte", "Unilever", "EDP", "Farfetch"],
        },
        "deadlines": [
            {"round": "Round 1", "date": "2025-11-30", "decision_date": "2026-01-15"},
            {"round": "Round 2", "date": "2026-02-28", "decision_date": "2026-04-15"},
            {"round": "Round 3", "date": "2026-05-31", "decision_date": "2026-06-30"},
        ],
        "admission_deadlines": [
            {"round": "Round 1", "deadline": "November 30, 2025", "decision": "January 15, 2026"},
            {"round": "Round 2", "deadline": "February 28, 2026", "decision": "April 15, 2026"},
            {"round": "Round 3", "deadline": "May 31, 2026", "decision": "June 30, 2026"},
        ],
        "application_questions": [
            "What are your short and long-term career goals and how will the Catolica Lisbon MBA help you achieve them?",
            "Describe a professional situation where you demonstrated leadership and impact.",
        ],
        "scholarships": [
            {"name": "Catolica MBA Merit Scholarship", "amount_usd": 10000, "criteria": "Academic excellence and GMAT score"},
            {"name": "Women in Business Scholarship", "amount_usd": 7000, "criteria": "Outstanding women candidates"},
        ],
        "class_profile": {
            "median_gmat": 640,
            "median_gre": None,
            "mean_gpa": 3.3,
            "women_pct": 40.0,
            "international_pct": 70.0,
            "underrepresented_minority_pct": None,
            "avg_work_experience_years": 6.0,
        },
        "application_fee_usd": 110,
        "application_url": "https://www.clsbe.lisboa.ucp.pt/mba",
        "confidence": 0.5,
    },
    "ebs_germany": {
        "name": "EBS Universitat fur Wirtschaft und Recht",
        "gmat_avg": 620,
        "acceptance_rate": 35.0,
        "class_size": 30,
        "tuition_usd": 38000,
        "median_salary": "$75,000",
        "program_duration": "15-month full-time",
        "program_format": "Full-Time MBA",
        "program_length_months": 15,
        "degree_type": "MBA",
        "stem_designated": False,
        "specializations": ["Finance", "Automotive", "Real Estate", "Digital Strategy", "Family Business"],
        "admission_requirements": {
            "gmat_gre": "Average GMAT: 620 (GMAT/GRE accepted)",
            "work_experience": "3+ years required",
            "avg_work_experience": "5 years",
            "english_proficiency": "TOEFL 90+ / IELTS 6.5+",
            "transcripts": "Official transcripts required",
            "recommendations": "2 professional recommendations required",
            "resume": "Current resume/CV required",
            "interview": "Required for shortlisted candidates",
            "application_fee": "EUR 100 (~$110)",
        },
        "program_details": {
            "duration": "15-month full-time",
            "format": "Full-Time, In-Person",
            "total_credits": 90,
            "core_courses": 12,
            "elective_courses": "20+ options",
            "class_size": 30,
            "avg_age": 30,
            "female_percentage": "35%",
            "international_percentage": "70%",
            "countries_represented": 20,
            "stem_designated": False,
            "start_date": "October",
        },
        "unique_features": [
            "Located in Germany's Rhine-Main financial region near Frankfurt",
            "Strong focus on family business and Mittelstand management",
            "Unique automotive and real estate specialization tracks",
            "Germany's oldest private business university",
            "Close industry ties with German DAX companies",
        ],
        "placement_stats": {
            "employment_rate_3mo_pct": 88.0,
            "median_base_salary_usd": 75000,
            "median_signing_bonus_usd": 5000,
            "top_industries": ["Consulting", "Finance", "Automotive", "Technology", "Real Estate"],
            "top_employers": ["Deutsche Bank", "BMW", "Roland Berger", "Porsche", "SAP"],
        },
        "deadlines": [
            {"round": "Round 1", "date": "2026-01-31", "decision_date": "2026-03-15"},
            {"round": "Round 2", "date": "2026-04-30", "decision_date": "2026-06-15"},
            {"round": "Round 3", "date": "2026-07-31", "decision_date": "2026-08-31"},
        ],
        "admission_deadlines": [
            {"round": "Round 1", "deadline": "January 31, 2026", "decision": "March 15, 2026"},
            {"round": "Round 2", "deadline": "April 30, 2026", "decision": "June 15, 2026"},
            {"round": "Round 3", "deadline": "July 31, 2026", "decision": "August 31, 2026"},
        ],
        "application_questions": [
            "Why do you want to pursue an MBA at EBS and how does it fit your career plans?",
            "Describe a challenging situation from your professional life and what you learned from it.",
        ],
        "scholarships": [
            {"name": "EBS MBA Scholarship", "amount_usd": 12000, "criteria": "Academic excellence and GMAT score"},
            {"name": "EBS International Diversity Award", "amount_usd": 8000, "criteria": "International diversity"},
        ],
        "class_profile": {
            "median_gmat": 620,
            "median_gre": None,
            "mean_gpa": 3.2,
            "women_pct": 35.0,
            "international_pct": 70.0,
            "underrepresented_minority_pct": None,
            "avg_work_experience_years": 5.0,
        },
        "application_fee_usd": 110,
        "application_url": "https://www.ebs.edu/en/programs/mba",
        "confidence": 0.4,
    },
    "pforzheim_germany": {
        "name": "Pforzheim University Business School",
        "gmat_avg": 580,
        "acceptance_rate": 40.0,
        "class_size": 25,
        "tuition_usd": 22000,
        "median_salary": "$65,000",
        "program_duration": "24-month part-time or 18-month full-time",
        "program_format": "Full-Time / Part-Time MBA",
        "program_length_months": 18,
        "degree_type": "MBA",
        "stem_designated": False,
        "specializations": ["International Management", "Innovation", "Sustainability", "Digital Business"],
        "admission_requirements": {
            "gmat_gre": "GMAT 550+ recommended (GMAT/GRE accepted)",
            "work_experience": "2+ years required",
            "avg_work_experience": "4 years",
            "english_proficiency": "TOEFL 90+ / IELTS 6.5+",
            "transcripts": "Official transcripts required",
            "recommendations": "2 professional recommendations",
            "resume": "Current resume/CV required",
            "interview": "Required",
            "application_fee": "EUR 50 (~$55)",
        },
        "program_details": {
            "duration": "18-month full-time or 24-month part-time",
            "format": "Full-Time / Part-Time, In-Person",
            "total_credits": 90,
            "core_courses": 10,
            "elective_courses": "12+ options",
            "class_size": 25,
            "avg_age": 29,
            "female_percentage": "38%",
            "international_percentage": "65%",
            "countries_represented": 15,
            "stem_designated": False,
            "start_date": "October",
        },
        "unique_features": [
            "AACSB accredited - one of few German universities of applied sciences with this credential",
            "Strong focus on German Mittelstand and manufacturing sector",
            "Located in Baden-Wurttemberg's innovation corridor near Stuttgart",
            "Affordable tuition compared to private German business schools",
            "International Management focus with diverse cohort",
        ],
        "placement_stats": {
            "employment_rate_3mo_pct": 90.0,
            "median_base_salary_usd": 65000,
            "median_signing_bonus_usd": None,
            "top_industries": ["Manufacturing", "Automotive", "Consulting", "Technology", "Finance"],
            "top_employers": ["Porsche", "Bosch", "Daimler", "Hugo Boss", "SAP"],
        },
        "deadlines": [
            {"round": "Round 1", "date": "2026-03-31", "decision_date": "2026-05-15"},
            {"round": "Round 2", "date": "2026-06-30", "decision_date": "2026-08-15"},
        ],
        "admission_deadlines": [
            {"round": "Round 1", "deadline": "March 31, 2026", "decision": "May 15, 2026"},
            {"round": "Round 2", "deadline": "June 30, 2026", "decision": "August 15, 2026"},
        ],
        "application_questions": [
            "Describe your career goals and how the Pforzheim MBA fits into your plans.",
        ],
        "scholarships": [
            {"name": "DAAD Scholarship", "amount_usd": 10000, "criteria": "International students from developing countries"},
            {"name": "Pforzheim Merit Award", "amount_usd": 5000, "criteria": "Academic excellence"},
        ],
        "class_profile": {
            "median_gmat": 580,
            "median_gre": None,
            "mean_gpa": 3.1,
            "women_pct": 38.0,
            "international_pct": 65.0,
            "underrepresented_minority_pct": None,
            "avg_work_experience_years": 4.0,
        },
        "application_fee_usd": 55,
        "application_url": "https://businesspf.hs-pforzheim.de/en/programs/master/mba",
        "confidence": 0.4,
    },
}


def main():
    with open(DB_PATH, "r", encoding="utf-8") as f:
        db = json.load(f)

    original_count = len(db)
    print(f"Schools in DB before enrichment: {original_count}")

    enriched = []
    for school_id, data in ENRICHMENTS.items():
        if school_id not in db:
            print(f"  WARN: {school_id} not found in DB - skipping enrichment")
            continue

        existing = db[school_id]
        # Merge enrichment data into existing entry
        for key, val in data.items():
            if val is None:
                continue
            if key == "name":
                # Keep existing name
                continue
            if isinstance(val, dict) and isinstance(existing.get(key), dict):
                for k2, v2 in val.items():
                    if v2 is not None:
                        existing[key][k2] = v2
            else:
                existing[key] = val

        # Update meta
        if "_meta" in existing:
            existing["_meta"]["enriched_at"] = datetime.now(timezone.utc).isoformat()
            existing["_meta"]["confidence"] = data.get("confidence", 0.5)
        existing["confidence"] = data.get("confidence", 0.5)

        db[school_id] = existing
        enriched.append(school_id)
        print(f"  Enriched: {school_id} ({existing['name']})")

    # Save
    with open(DB_PATH, "w", encoding="utf-8") as f:
        json.dump(db, f, indent=2, ensure_ascii=False)

    final_count = len(db)
    print(f"\nSchools in DB after: {final_count}")
    print(f"Schools enriched: {len(enriched)}")

    # Print summary table
    print(f"\n{'ID':<25} {'Name':<55} {'Tuition':>10} {'GMAT':>6} {'Size':>6} {'Accept':>8}")
    print("-" * 120)
    for sid in enriched:
        entry = db[sid]
        tuition = str(entry.get("tuition_usd") or "N/A")
        gmat = str(entry.get("gmat_avg") or "N/A")
        size = str(entry.get("class_size") or "N/A")
        accept = str(entry.get("acceptance_rate") or "N/A")
        print(f"{sid:<25} {entry['name']:<55} {tuition:>10} {gmat:>6} {size:>6} {accept:>8}")


if __name__ == "__main__":
    main()
