# MBA Rankings 2025 — Combined FT + QS
# Primary source: Financial Times Global MBA Ranking 2025 (top 100, all schools)
# Supplementary: QS Global MBA Rankings 2025 (for schools not in FT top 100)
# Compiled: 2026-03-16

# ─────────────────────────────────────────────────────────────────
# FT Global MBA Ranking 2025 — Full Top 100
# Source: https://www.iima.ac.in/sites/default/files/2025-02/FT%20Global%20MBA%20Ranking%202025.pdf
# Note: Stanford GSB excluded by FT due to insufficient alumni survey responses.
# ─────────────────────────────────────────────────────────────────

FT_MBA_2025 = [
    {"ft_rank": 1,   "name": "University of Pennsylvania: Wharton",                          "country": "US",          "city": "Philadelphia"},
    {"ft_rank": 2,   "name": "Columbia Business School",                                     "country": "US",          "city": "New York"},
    {"ft_rank": 3,   "name": "IESE Business School",                                         "country": "Spain",        "city": "Barcelona"},
    {"ft_rank": 4,   "name": "INSEAD",                                                        "country": "France",       "city": "Fontainebleau"},
    {"ft_rank": 4,   "name": "SDA Bocconi School of Management",                             "country": "Italy",        "city": "Milan"},
    {"ft_rank": 6,   "name": "MIT: Sloan",                                                    "country": "US",          "city": "Cambridge"},
    {"ft_rank": 7,   "name": "London Business School",                                        "country": "UK",           "city": "London"},
    {"ft_rank": 8,   "name": "Esade Business School",                                         "country": "Spain",        "city": "Barcelona"},
    {"ft_rank": 9,   "name": "HEC Paris",                                                     "country": "France",       "city": "Paris"},
    {"ft_rank": 10,  "name": "Northwestern University: Kellogg School of Management",         "country": "US",          "city": "Evanston"},
    {"ft_rank": 11,  "name": "Duke University: Fuqua School of Business",                     "country": "US",          "city": "Durham"},
    {"ft_rank": 12,  "name": "CEIBS",                                                         "country": "China",        "city": "Shanghai"},
    {"ft_rank": 13,  "name": "Harvard Business School",                                       "country": "US",          "city": "Boston"},
    {"ft_rank": 13,  "name": "Cornell University: Johnson",                                   "country": "US",          "city": "Ithaca"},
    {"ft_rank": 15,  "name": "UC Berkeley: Haas",                                             "country": "US",          "city": "Berkeley"},
    {"ft_rank": 15,  "name": "Shanghai University of Finance and Economics: College of Business", "country": "China",   "city": "Shanghai"},
    {"ft_rank": 17,  "name": "University of Chicago: Booth",                                  "country": "US",          "city": "Chicago"},
    {"ft_rank": 18,  "name": "IE Business School",                                            "country": "Spain",        "city": "Madrid"},
    {"ft_rank": 19,  "name": "UCLA Anderson School of Management",                            "country": "US",          "city": "Los Angeles"},
    {"ft_rank": 20,  "name": "Dartmouth College: Tuck",                                       "country": "US",          "city": "Hanover"},
    {"ft_rank": 20,  "name": "University of Virginia: Darden",                                "country": "US",          "city": "Charlottesville"},
    {"ft_rank": 22,  "name": "IMD",                                                           "country": "Switzerland",  "city": "Lausanne"},
    {"ft_rank": 22,  "name": "Nanyang Business School, NTU Singapore",                        "country": "Singapore",    "city": "Singapore"},
    {"ft_rank": 24,  "name": "Yale School of Management",                                     "country": "US",          "city": "New Haven"},
    {"ft_rank": 25,  "name": "Peking University: Guanghua",                                   "country": "China",        "city": "Beijing"},
    {"ft_rank": 26,  "name": "University of Oxford: Saïd",                                    "country": "UK",           "city": "Oxford"},
    {"ft_rank": 27,  "name": "Indian School of Business",                                     "country": "India",        "city": "Hyderabad"},
    {"ft_rank": 28,  "name": "ESCP Business School",                                          "country": "France",       "city": "Paris"},
    {"ft_rank": 29,  "name": "University of Michigan: Ross",                                  "country": "US",          "city": "Ann Arbor"},
    {"ft_rank": 30,  "name": "Fudan University School of Management",                         "country": "China",        "city": "Shanghai"},
    {"ft_rank": 31,  "name": "New York University: Stern",                                    "country": "US",          "city": "New York"},
    {"ft_rank": 31,  "name": "Indian Institute of Management Ahmedabad",                      "country": "India",        "city": "Ahmedabad"},
    {"ft_rank": 31,  "name": "Tongji University School of Economics and Management",          "country": "China",        "city": "Shanghai"},
    {"ft_rank": 34,  "name": "University of Washington: Michael G. Foster",                   "country": "US",          "city": "Seattle"},
    {"ft_rank": 35,  "name": "University of Cambridge: Judge",                                "country": "UK",           "city": "Cambridge"},
    {"ft_rank": 36,  "name": "HKUST Business School",                                         "country": "Hong Kong",    "city": "Hong Kong"},
    {"ft_rank": 37,  "name": "National University of Singapore Business School",              "country": "Singapore",    "city": "Singapore"},
    {"ft_rank": 38,  "name": "Imperial College Business School",                              "country": "UK",           "city": "London"},
    {"ft_rank": 39,  "name": "Rice University: Jones",                                        "country": "US",          "city": "Houston"},
    {"ft_rank": 39,  "name": "University of Texas at Austin: McCombs",                        "country": "US",          "city": "Austin"},
    {"ft_rank": 41,  "name": "HKU Business School",                                           "country": "Hong Kong",    "city": "Hong Kong"},
    {"ft_rank": 42,  "name": "Washington University: Olin",                                   "country": "US",          "city": "St. Louis"},
    {"ft_rank": 43,  "name": "Georgetown University: McDonough",                              "country": "US",          "city": "Washington DC"},
    {"ft_rank": 44,  "name": "EMLyon Business School",                                        "country": "France",       "city": "Lyon"},
    {"ft_rank": 45,  "name": "Emory University: Goizueta",                                    "country": "US",          "city": "Atlanta"},
    {"ft_rank": 46,  "name": "Alliance Manchester Business School",                           "country": "UK",           "city": "Manchester"},
    {"ft_rank": 47,  "name": "Essec Business School",                                         "country": "France",       "city": "Cergy"},
    {"ft_rank": 48,  "name": "University of Florida: Warrington",                             "country": "US",          "city": "Gainesville"},
    {"ft_rank": 49,  "name": "Carnegie Mellon: Tepper",                                       "country": "US",          "city": "Pittsburgh"},
    {"ft_rank": 50,  "name": "University of Southern California: Marshall",                   "country": "US",          "city": "Los Angeles"},
    {"ft_rank": 51,  "name": "University of North Carolina: Kenan-Flagler",                   "country": "US",          "city": "Chapel Hill"},
    {"ft_rank": 52,  "name": "Vanderbilt University: Owen",                                   "country": "US",          "city": "Nashville"},
    {"ft_rank": 53,  "name": "University of California at Irvine: Merage",                    "country": "US",          "city": "Irvine"},
    {"ft_rank": 54,  "name": "University of Texas at Dallas: Jindal",                         "country": "US",          "city": "Dallas"},
    {"ft_rank": 55,  "name": "University of Georgia: Terry",                                  "country": "US",          "city": "Athens"},
    {"ft_rank": 56,  "name": "Rotterdam School of Management, Erasmus University",            "country": "Netherlands",  "city": "Rotterdam"},
    {"ft_rank": 57,  "name": "Indian Institute of Management Bangalore",                      "country": "India",        "city": "Bangalore"},
    {"ft_rank": 58,  "name": "Georgia Tech Scheller College of Business",                     "country": "US",          "city": "Atlanta"},
    {"ft_rank": 59,  "name": "Arizona State University: WP Carey",                            "country": "US",          "city": "Tempe"},
    {"ft_rank": 60,  "name": "University of Rochester: Simon Business School",                "country": "US",          "city": "Rochester"},
    {"ft_rank": 61,  "name": "Indian Institute of Management Calcutta",                       "country": "India",        "city": "Kolkata"},
    {"ft_rank": 62,  "name": "Warwick Business School",                                       "country": "UK",           "city": "Coventry"},
    {"ft_rank": 63,  "name": "University of St Gallen",                                       "country": "Switzerland",  "city": "St. Gallen"},
    {"ft_rank": 64,  "name": "Edhec Business School",                                         "country": "France",       "city": "Lille"},
    {"ft_rank": 65,  "name": "CUHK Business School",                                          "country": "Hong Kong",    "city": "Hong Kong"},
    {"ft_rank": 66,  "name": "WHU — Otto Beisheim School of Management",                      "country": "Germany",      "city": "Vallendar"},
    {"ft_rank": 67,  "name": "Bayes Business School (formerly Cass)",                         "country": "UK",           "city": "London"},
    {"ft_rank": 67,  "name": "AGSM at UNSW Business School",                                  "country": "Australia",    "city": "Sydney"},
    {"ft_rank": 69,  "name": "Indian Institute of Management Indore",                         "country": "India",        "city": "Indore"},
    {"ft_rank": 70,  "name": "Texas A&M University: Mays",                                    "country": "US",          "city": "College Station"},
    {"ft_rank": 71,  "name": "Mannheim Business School",                                      "country": "Germany",      "city": "Mannheim"},
    {"ft_rank": 71,  "name": "Indian Institute of Management Lucknow",                        "country": "India",        "city": "Lucknow"},
    {"ft_rank": 73,  "name": "University College Dublin: Smurfit",                            "country": "Ireland",      "city": "Dublin"},
    {"ft_rank": 74,  "name": "Boston University Questrom School of Business",                 "country": "US",          "city": "Boston"},
    {"ft_rank": 75,  "name": "University of Notre Dame: Mendoza",                             "country": "US",          "city": "Notre Dame"},
    {"ft_rank": 76,  "name": "University of Toronto: Rotman",                                 "country": "Canada",       "city": "Toronto"},
    {"ft_rank": 77,  "name": "The Lisbon MBA Católica | Nova",                                "country": "Portugal",     "city": "Lisbon"},
    {"ft_rank": 78,  "name": "Fordham University: Gabelli",                                   "country": "US",          "city": "New York"},
    {"ft_rank": 79,  "name": "Queen's University: Smith",                                     "country": "Canada",       "city": "Kingston"},
    {"ft_rank": 80,  "name": "William & Mary: Mason",                                         "country": "US",          "city": "Williamsburg"},
    {"ft_rank": 80,  "name": "ESMT Berlin",                                                   "country": "Germany",      "city": "Berlin"},
    {"ft_rank": 82,  "name": "Cranfield School of Management",                                "country": "UK",           "city": "Cranfield"},
    {"ft_rank": 83,  "name": "Brigham Young University: Marriott",                            "country": "US",          "city": "Provo"},
    {"ft_rank": 83,  "name": "Babson College: Olin",                                          "country": "US",          "city": "Wellesley"},
    {"ft_rank": 83,  "name": "XLRI — Xavier School of Management",                            "country": "India",        "city": "Jamshedpur"},
    {"ft_rank": 86,  "name": "Durham University Business School",                             "country": "UK",           "city": "Durham"},
    {"ft_rank": 86,  "name": "Western University: Ivey",                                      "country": "Canada",       "city": "London"},
    {"ft_rank": 86,  "name": "Indian Institute of Management Kozhikode",                      "country": "India",        "city": "Kozhikode"},
    {"ft_rank": 89,  "name": "Grenoble Ecole de Management",                                  "country": "France",       "city": "Grenoble"},
    {"ft_rank": 90,  "name": "Audencia",                                                      "country": "France",       "city": "Nantes"},
    {"ft_rank": 91,  "name": "University of Edinburgh Business School",                       "country": "UK",           "city": "Edinburgh"},
    {"ft_rank": 92,  "name": "Hult International Business School",                            "country": "US",          "city": "Boston"},
    {"ft_rank": 93,  "name": "Copenhagen Business School (CBS)",                              "country": "Denmark",      "city": "Copenhagen"},
    {"ft_rank": 94,  "name": "McGill University: Desautels",                                  "country": "Canada",       "city": "Montreal"},
    {"ft_rank": 95,  "name": "University of British Columbia: Sauder",                        "country": "Canada",       "city": "Vancouver"},
    {"ft_rank": 96,  "name": "Frankfurt School of Finance and Management",                    "country": "Germany",      "city": "Frankfurt"},
    {"ft_rank": 97,  "name": "University of Glasgow: Adam Smith",                             "country": "UK",           "city": "Glasgow"},
    {"ft_rank": 98,  "name": "Sungkyunkwan University GSB",                                   "country": "South Korea",  "city": "Seoul"},
    {"ft_rank": 99,  "name": "Miami Herbert Business School",                                 "country": "US",          "city": "Coral Gables"},
    {"ft_rank": 100, "name": "Eada Business School Barcelona",                                "country": "Spain",        "city": "Barcelona"},
]

# ─────────────────────────────────────────────────────────────────
# QS Global MBA Rankings 2025 — Schools NOT in FT top 100
# Source: https://www.topuniversities.com/mba-rankings/global/2025
# Note: QS ranks 1-30 extracted. Stanford GSB is QS #1 (absent from FT).
# Tsinghua is QS #29 (not in FT top 100).
# ─────────────────────────────────────────────────────────────────

QS_MBA_2025_ADDITIONAL = [
    # Stanford absent from FT — included here from QS
    {"qs_rank": 1,  "name": "Stanford Graduate School of Business",                           "country": "US",          "city": "Stanford"},
    # Tsinghua not in FT top 100
    {"qs_rank": 29, "name": "Tsinghua University: School of Economics and Management",        "country": "China",        "city": "Beijing"},
]

# ─────────────────────────────────────────────────────────────────
# COMBINED LIST — 100 FT schools + 2 QS-only additions = 102 schools
# Use this for seeding the school database.
# Each entry tagged with source for data confidence scoring.
# ─────────────────────────────────────────────────────────────────

COMBINED_MBA_SCHOOLS = [
    # ── QS-only (not in FT top 100) ─────────────────────────────
    {"rank": 1,   "name": "Stanford Graduate School of Business",                             "country": "US",          "city": "Stanford",         "source": "QS_2025",    "qs_rank": 1},

    # ── FT 2025 Top 100 ─────────────────────────────────────────
    {"rank": 1,   "name": "University of Pennsylvania: Wharton",                              "country": "US",          "city": "Philadelphia",      "source": "FT_2025",    "ft_rank": 1},
    {"rank": 2,   "name": "Columbia Business School",                                         "country": "US",          "city": "New York",          "source": "FT_2025",    "ft_rank": 2},
    {"rank": 3,   "name": "IESE Business School",                                             "country": "Spain",        "city": "Barcelona",         "source": "FT_2025",    "ft_rank": 3},
    {"rank": 4,   "name": "INSEAD",                                                           "country": "France",       "city": "Fontainebleau",     "source": "FT_2025",    "ft_rank": 4},
    {"rank": 4,   "name": "SDA Bocconi School of Management",                                 "country": "Italy",        "city": "Milan",             "source": "FT_2025",    "ft_rank": 4},
    {"rank": 6,   "name": "MIT: Sloan",                                                       "country": "US",          "city": "Cambridge",         "source": "FT_2025",    "ft_rank": 6},
    {"rank": 7,   "name": "London Business School",                                           "country": "UK",           "city": "London",            "source": "FT_2025",    "ft_rank": 7},
    {"rank": 8,   "name": "Esade Business School",                                            "country": "Spain",        "city": "Barcelona",         "source": "FT_2025",    "ft_rank": 8},
    {"rank": 9,   "name": "HEC Paris",                                                        "country": "France",       "city": "Paris",             "source": "FT_2025",    "ft_rank": 9},
    {"rank": 10,  "name": "Northwestern University: Kellogg School of Management",            "country": "US",          "city": "Evanston",          "source": "FT_2025",    "ft_rank": 10},
    {"rank": 11,  "name": "Duke University: Fuqua School of Business",                        "country": "US",          "city": "Durham",            "source": "FT_2025",    "ft_rank": 11},
    {"rank": 12,  "name": "CEIBS",                                                            "country": "China",        "city": "Shanghai",          "source": "FT_2025",    "ft_rank": 12},
    {"rank": 13,  "name": "Harvard Business School",                                          "country": "US",          "city": "Boston",            "source": "FT_2025",    "ft_rank": 13},
    {"rank": 13,  "name": "Cornell University: Johnson",                                      "country": "US",          "city": "Ithaca",            "source": "FT_2025",    "ft_rank": 13},
    {"rank": 15,  "name": "UC Berkeley: Haas",                                                "country": "US",          "city": "Berkeley",          "source": "FT_2025",    "ft_rank": 15},
    {"rank": 15,  "name": "Shanghai University of Finance and Economics: College of Business","country": "China",        "city": "Shanghai",          "source": "FT_2025",    "ft_rank": 15},
    {"rank": 17,  "name": "University of Chicago: Booth",                                     "country": "US",          "city": "Chicago",           "source": "FT_2025",    "ft_rank": 17},
    {"rank": 18,  "name": "IE Business School",                                               "country": "Spain",        "city": "Madrid",            "source": "FT_2025",    "ft_rank": 18},
    {"rank": 19,  "name": "UCLA Anderson School of Management",                               "country": "US",          "city": "Los Angeles",       "source": "FT_2025",    "ft_rank": 19},
    {"rank": 20,  "name": "Dartmouth College: Tuck",                                          "country": "US",          "city": "Hanover",           "source": "FT_2025",    "ft_rank": 20},
    {"rank": 20,  "name": "University of Virginia: Darden",                                   "country": "US",          "city": "Charlottesville",   "source": "FT_2025",    "ft_rank": 20},
    {"rank": 22,  "name": "IMD",                                                              "country": "Switzerland",  "city": "Lausanne",          "source": "FT_2025",    "ft_rank": 22},
    {"rank": 22,  "name": "Nanyang Business School, NTU Singapore",                           "country": "Singapore",    "city": "Singapore",         "source": "FT_2025",    "ft_rank": 22},
    {"rank": 24,  "name": "Yale School of Management",                                        "country": "US",          "city": "New Haven",         "source": "FT_2025",    "ft_rank": 24},
    {"rank": 25,  "name": "Peking University: Guanghua",                                      "country": "China",        "city": "Beijing",           "source": "FT_2025",    "ft_rank": 25},
    {"rank": 26,  "name": "University of Oxford: Saïd",                                       "country": "UK",           "city": "Oxford",            "source": "FT_2025",    "ft_rank": 26},
    {"rank": 27,  "name": "Indian School of Business",                                        "country": "India",        "city": "Hyderabad",         "source": "FT_2025",    "ft_rank": 27},
    {"rank": 28,  "name": "ESCP Business School",                                             "country": "France",       "city": "Paris",             "source": "FT_2025",    "ft_rank": 28},
    {"rank": 29,  "name": "University of Michigan: Ross",                                     "country": "US",          "city": "Ann Arbor",         "source": "FT_2025",    "ft_rank": 29},
    {"rank": 29,  "name": "Tsinghua University: School of Economics and Management",          "country": "China",        "city": "Beijing",           "source": "QS_2025",    "qs_rank": 29},
    {"rank": 30,  "name": "Fudan University School of Management",                            "country": "China",        "city": "Shanghai",          "source": "FT_2025",    "ft_rank": 30},
    {"rank": 31,  "name": "New York University: Stern",                                       "country": "US",          "city": "New York",          "source": "FT_2025",    "ft_rank": 31},
    {"rank": 31,  "name": "Indian Institute of Management Ahmedabad",                         "country": "India",        "city": "Ahmedabad",         "source": "FT_2025",    "ft_rank": 31},
    {"rank": 31,  "name": "Tongji University School of Economics and Management",             "country": "China",        "city": "Shanghai",          "source": "FT_2025",    "ft_rank": 31},
    {"rank": 34,  "name": "University of Washington: Michael G. Foster",                      "country": "US",          "city": "Seattle",           "source": "FT_2025",    "ft_rank": 34},
    {"rank": 35,  "name": "University of Cambridge: Judge",                                   "country": "UK",           "city": "Cambridge",         "source": "FT_2025",    "ft_rank": 35},
    {"rank": 36,  "name": "HKUST Business School",                                            "country": "Hong Kong",    "city": "Hong Kong",         "source": "FT_2025",    "ft_rank": 36},
    {"rank": 37,  "name": "National University of Singapore Business School",                 "country": "Singapore",    "city": "Singapore",         "source": "FT_2025",    "ft_rank": 37},
    {"rank": 38,  "name": "Imperial College Business School",                                 "country": "UK",           "city": "London",            "source": "FT_2025",    "ft_rank": 38},
    {"rank": 39,  "name": "Rice University: Jones",                                           "country": "US",          "city": "Houston",           "source": "FT_2025",    "ft_rank": 39},
    {"rank": 39,  "name": "University of Texas at Austin: McCombs",                           "country": "US",          "city": "Austin",            "source": "FT_2025",    "ft_rank": 39},
    {"rank": 41,  "name": "HKU Business School",                                              "country": "Hong Kong",    "city": "Hong Kong",         "source": "FT_2025",    "ft_rank": 41},
    {"rank": 42,  "name": "Washington University: Olin",                                      "country": "US",          "city": "St. Louis",         "source": "FT_2025",    "ft_rank": 42},
    {"rank": 43,  "name": "Georgetown University: McDonough",                                 "country": "US",          "city": "Washington DC",     "source": "FT_2025",    "ft_rank": 43},
    {"rank": 44,  "name": "EMLyon Business School",                                           "country": "France",       "city": "Lyon",              "source": "FT_2025",    "ft_rank": 44},
    {"rank": 45,  "name": "Emory University: Goizueta",                                       "country": "US",          "city": "Atlanta",           "source": "FT_2025",    "ft_rank": 45},
    {"rank": 46,  "name": "Alliance Manchester Business School",                              "country": "UK",           "city": "Manchester",        "source": "FT_2025",    "ft_rank": 46},
    {"rank": 47,  "name": "ESSEC Business School",                                            "country": "France",       "city": "Cergy",             "source": "FT_2025",    "ft_rank": 47},
    {"rank": 48,  "name": "University of Florida: Warrington",                                "country": "US",          "city": "Gainesville",       "source": "FT_2025",    "ft_rank": 48},
    {"rank": 49,  "name": "Carnegie Mellon: Tepper",                                          "country": "US",          "city": "Pittsburgh",        "source": "FT_2025",    "ft_rank": 49},
    {"rank": 50,  "name": "University of Southern California: Marshall",                      "country": "US",          "city": "Los Angeles",       "source": "FT_2025",    "ft_rank": 50},
    {"rank": 51,  "name": "University of North Carolina: Kenan-Flagler",                      "country": "US",          "city": "Chapel Hill",       "source": "FT_2025",    "ft_rank": 51},
    {"rank": 52,  "name": "Vanderbilt University: Owen",                                      "country": "US",          "city": "Nashville",         "source": "FT_2025",    "ft_rank": 52},
    {"rank": 53,  "name": "University of California at Irvine: Merage",                       "country": "US",          "city": "Irvine",            "source": "FT_2025",    "ft_rank": 53},
    {"rank": 54,  "name": "University of Texas at Dallas: Jindal",                            "country": "US",          "city": "Dallas",            "source": "FT_2025",    "ft_rank": 54},
    {"rank": 55,  "name": "University of Georgia: Terry",                                     "country": "US",          "city": "Athens",            "source": "FT_2025",    "ft_rank": 55},
    {"rank": 56,  "name": "Rotterdam School of Management, Erasmus University",               "country": "Netherlands",  "city": "Rotterdam",         "source": "FT_2025",    "ft_rank": 56},
    {"rank": 57,  "name": "Indian Institute of Management Bangalore",                         "country": "India",        "city": "Bangalore",         "source": "FT_2025",    "ft_rank": 57},
    {"rank": 58,  "name": "Georgia Tech Scheller College of Business",                        "country": "US",          "city": "Atlanta",           "source": "FT_2025",    "ft_rank": 58},
    {"rank": 59,  "name": "Arizona State University: WP Carey",                               "country": "US",          "city": "Tempe",             "source": "FT_2025",    "ft_rank": 59},
    {"rank": 60,  "name": "University of Rochester: Simon Business School",                   "country": "US",          "city": "Rochester",         "source": "FT_2025",    "ft_rank": 60},
    {"rank": 61,  "name": "Indian Institute of Management Calcutta",                          "country": "India",        "city": "Kolkata",           "source": "FT_2025",    "ft_rank": 61},
    {"rank": 62,  "name": "Warwick Business School",                                          "country": "UK",           "city": "Coventry",          "source": "FT_2025",    "ft_rank": 62},
    {"rank": 63,  "name": "University of St Gallen",                                          "country": "Switzerland",  "city": "St. Gallen",        "source": "FT_2025",    "ft_rank": 63},
    {"rank": 64,  "name": "Edhec Business School",                                            "country": "France",       "city": "Lille",             "source": "FT_2025",    "ft_rank": 64},
    {"rank": 65,  "name": "CUHK Business School",                                             "country": "Hong Kong",    "city": "Hong Kong",         "source": "FT_2025",    "ft_rank": 65},
    {"rank": 66,  "name": "WHU — Otto Beisheim School of Management",                         "country": "Germany",      "city": "Vallendar",         "source": "FT_2025",    "ft_rank": 66},
    {"rank": 67,  "name": "Bayes Business School",                                            "country": "UK",           "city": "London",            "source": "FT_2025",    "ft_rank": 67},
    {"rank": 67,  "name": "AGSM at UNSW Business School",                                     "country": "Australia",    "city": "Sydney",            "source": "FT_2025",    "ft_rank": 67},
    {"rank": 69,  "name": "Indian Institute of Management Indore",                            "country": "India",        "city": "Indore",            "source": "FT_2025",    "ft_rank": 69},
    {"rank": 70,  "name": "Texas A&M University: Mays",                                       "country": "US",          "city": "College Station",   "source": "FT_2025",    "ft_rank": 70},
    {"rank": 71,  "name": "Mannheim Business School",                                         "country": "Germany",      "city": "Mannheim",          "source": "FT_2025",    "ft_rank": 71},
    {"rank": 71,  "name": "Indian Institute of Management Lucknow",                           "country": "India",        "city": "Lucknow",           "source": "FT_2025",    "ft_rank": 71},
    {"rank": 73,  "name": "University College Dublin: Smurfit",                               "country": "Ireland",      "city": "Dublin",            "source": "FT_2025",    "ft_rank": 73},
    {"rank": 74,  "name": "Boston University Questrom School of Business",                    "country": "US",          "city": "Boston",            "source": "FT_2025",    "ft_rank": 74},
    {"rank": 75,  "name": "University of Notre Dame: Mendoza",                                "country": "US",          "city": "Notre Dame",        "source": "FT_2025",    "ft_rank": 75},
    {"rank": 76,  "name": "University of Toronto: Rotman",                                    "country": "Canada",       "city": "Toronto",           "source": "FT_2025",    "ft_rank": 76},
    {"rank": 77,  "name": "The Lisbon MBA Católica | Nova",                                   "country": "Portugal",     "city": "Lisbon",            "source": "FT_2025",    "ft_rank": 77},
    {"rank": 78,  "name": "Fordham University: Gabelli",                                      "country": "US",          "city": "New York",          "source": "FT_2025",    "ft_rank": 78},
    {"rank": 79,  "name": "Queen's University: Smith",                                        "country": "Canada",       "city": "Kingston",          "source": "FT_2025",    "ft_rank": 79},
    {"rank": 80,  "name": "William & Mary: Mason",                                            "country": "US",          "city": "Williamsburg",      "source": "FT_2025",    "ft_rank": 80},
    {"rank": 80,  "name": "ESMT Berlin",                                                      "country": "Germany",      "city": "Berlin",            "source": "FT_2025",    "ft_rank": 80},
    {"rank": 82,  "name": "Cranfield School of Management",                                   "country": "UK",           "city": "Cranfield",         "source": "FT_2025",    "ft_rank": 82},
    {"rank": 83,  "name": "Brigham Young University: Marriott",                               "country": "US",          "city": "Provo",             "source": "FT_2025",    "ft_rank": 83},
    {"rank": 83,  "name": "Babson College: Olin",                                             "country": "US",          "city": "Wellesley",         "source": "FT_2025",    "ft_rank": 83},
    {"rank": 83,  "name": "XLRI — Xavier School of Management",                               "country": "India",        "city": "Jamshedpur",        "source": "FT_2025",    "ft_rank": 83},
    {"rank": 86,  "name": "Durham University Business School",                                "country": "UK",           "city": "Durham",            "source": "FT_2025",    "ft_rank": 86},
    {"rank": 86,  "name": "Western University: Ivey",                                         "country": "Canada",       "city": "London",            "source": "FT_2025",    "ft_rank": 86},
    {"rank": 86,  "name": "Indian Institute of Management Kozhikode",                         "country": "India",        "city": "Kozhikode",         "source": "FT_2025",    "ft_rank": 86},
    {"rank": 89,  "name": "Grenoble Ecole de Management",                                     "country": "France",       "city": "Grenoble",          "source": "FT_2025",    "ft_rank": 89},
    {"rank": 90,  "name": "Audencia",                                                         "country": "France",       "city": "Nantes",            "source": "FT_2025",    "ft_rank": 90},
    {"rank": 91,  "name": "University of Edinburgh Business School",                          "country": "UK",           "city": "Edinburgh",         "source": "FT_2025",    "ft_rank": 91},
    {"rank": 92,  "name": "Hult International Business School",                               "country": "US",          "city": "Boston",            "source": "FT_2025",    "ft_rank": 92},
    {"rank": 93,  "name": "Copenhagen Business School",                                       "country": "Denmark",      "city": "Copenhagen",        "source": "FT_2025",    "ft_rank": 93},
    {"rank": 94,  "name": "McGill University: Desautels",                                     "country": "Canada",       "city": "Montreal",          "source": "FT_2025",    "ft_rank": 94},
    {"rank": 95,  "name": "University of British Columbia: Sauder",                           "country": "Canada",       "city": "Vancouver",         "source": "FT_2025",    "ft_rank": 95},
    {"rank": 96,  "name": "Frankfurt School of Finance and Management",                       "country": "Germany",      "city": "Frankfurt",         "source": "FT_2025",    "ft_rank": 96},
    {"rank": 97,  "name": "University of Glasgow: Adam Smith",                                "country": "UK",           "city": "Glasgow",           "source": "FT_2025",    "ft_rank": 97},
    {"rank": 98,  "name": "Sungkyunkwan University GSB",                                      "country": "South Korea",  "city": "Seoul",             "source": "FT_2025",    "ft_rank": 98},
    {"rank": 99,  "name": "Miami Herbert Business School",                                    "country": "US",          "city": "Coral Gables",      "source": "FT_2025",    "ft_rank": 99},
    {"rank": 100, "name": "Eada Business School Barcelona",                                   "country": "Spain",        "city": "Barcelona",         "source": "FT_2025",    "ft_rank": 100},
]

# Total: 102 unique schools (100 FT + Stanford GSB + Tsinghua from QS)
# Countries represented: US, UK, France, Spain, Germany, India, China, Singapore,
#   Switzerland, Hong Kong, Italy, Canada, Netherlands, Australia, Ireland,
#   Portugal, Denmark, South Korea
